# Generated by Django 4.2.6 on 2023-10-31 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroceryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('sku', models.CharField(max_length=200)),
                ('cost', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=200)),
                ('recipe_ingredients', models.ManyToManyField(to='groceries_app.groceryitem')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_name', models.CharField(max_length=200)),
                ('search_lowest_cost', models.BooleanField(default=False)),
                ('preferred_store', models.CharField(blank=True, choices=[('Krog', 'King Soopers/ City Market'), ('WalM', 'Walmart'), ('Sprt', 'Sprouts'), ('CosC', 'CostCo')], max_length=4)),
                ('recipes', models.ManyToManyField(to='groceries_app.recipe')),
            ],
        ),
    ]
