# Generated by Django 4.2.6 on 2023-10-31 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceries_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe_ingredients',
            field=models.ManyToManyField(related_name='recipes', to='groceries_app.groceryitem'),
        ),
    ]
