# Generated by Django 4.2.6 on 2023-11-20 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceries_app', '0004_recipe_creator_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
