name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Virtual Environment
      run: |
        source groceryApp/djvenv/bin/activate
      
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Remove existing Chromedriver
      run: sudo rm /usr/local/bin/chromedriver || true

    - name: Download and Install compatible Chromedriver
      run: |
        CHROMEDRIVER_VERSION="119.0.6045.159"  
        wget "https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip"
        unzip chromedriver_linux64.zip
        sudo mv chromedriver /usr/local/bin/
        sudo chmod +x /usr/local/bin/chromedriver

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r groceryApp/requirements.txt

    - name: Run Tests
      run: |
        python groceryApp/manage.py test groceries_app
